[providers]
node = "18"

[phases.install]
cmds = [
  "npm install",
  "cd backend(node) && npm install"
]

[phases.build]
cmds = [
  "cd backend(node) && npm run build"
]

[start]
cmd = "cd backend(node) && npm start"
